### ISSUE TITLE
Centralized bucklescript bindings

### ISSUE THREAD

**Issue by wokalski** [reasonml-community/index#4]
So BuckleTypes org is great but the current workflow for creating and consuming typings is hard to scale. If I want to use the binding I have to:

1. Discover it
2. install with npm
3. add to bsconfig

while hoping for version compatibility with whatever I use.

On the other hand of the spectrum a creator has to create a repo, add it to npm (or at least add package.json) and be willing to maintain it over time. Otherwise it gets abandoned and everybody is sad.

### Solution: consuming

The most straightforward<sup>1</sup> solution is to create a centralised repo for bindings. @ryyppy<sup>2</sup> suggested that we could copy the implementation from TypeScript 2.

How I imagine the perfect workflow is that there's a single `bucklescript` command - let's say `install` which pulls typings from the central repo/place and adds them to your project. I don't think it needs to do resolve version because it can either use `yarn.lock` or check module version directly in `node_modules`. You end up with typings added to your `bsconfig` and probably to `package.json`. afterwards you'd probably need to run `yarn`/`npm install` to actually pull those in.

### Solution: authoring

I'm not sure what's the perfect way to design publishing specs and vendoring specs. I imagine that typings need to be owned by the community. I'm not sure how to model it so that it's both easy to contribute to and maintains good quality.

### Let's discuss ideas before discussing the implementation

So before we bikeshed about particular implementation and how to resolve the problems with it, let's think about the workflow. I'll try to write down everything that we mentioned on Discord if I have time. Any contribution below is much appreciated.

---

1: not really straightforward
2: I don't know their github handle

**Comment by chenglou** [comment]
Centralized repo doesn't work for us. BS is a compiler so it has to compile every file. Plus some of them might have overlapping dependencies that don't resolve well.

The js dependencies should be modeled as actual package.json dependencies, not peerDependencies. For all we know, the implementation might have been gradually swapped out toward a pure bs impl. The natural deps deduping makes sure the user isn't requiring e.g. a react-router and a bs-react-router's different react-router.

For curation, we'd list a repo along with its stability. Everything under bs-* in npm, we can assume them to be from bucklescript. npm org also works but we don't have to do that immediately. BuckleTypes is the central org where you'll look for these things.

Authoring: I've got drafts that I haven't shared. Thanks for the reminder. Will do.

**Comment by wokalski** [comment]
How do we keep typing and package versions in sync?

bs would still have all the files. it would pull bindings based on installed deps.

Not sure if a curated listing is needed when a tool pulls the bindings automatically.

**Comment by chenglou** [comment]
The dep is modeled as a real dependency of the bindings. Unless you yourself also use that dep in a JS, and track master.

Pulling bindings and all seems like additional tooling and confusion points, I'm not sure about this. I'll let @ryyppy speak. Curation is still good though; it's what Reason's about too.

**Comment by wokalski** [comment]
I see. I approached the problem from a point of view of an existing codebase.

**Comment by ryyppy** [comment]
After giving it a second thought, I really would like to play around with bucklescript bindings more before I can really tell which approach is the better fit... A lot of problems w/ e.g. flow-typed arised with the limitations of the typechecker itself... I think OCaml is much better in that regard, so the workflow around it might be completely different and renders all my believes & knowledge obsolete.

If there should be some tooling around it (maybe by just checking for BuckleTypes repositories instead of central repo), I would definitely consider following user-stories:

- I want to be able to version lock my dependency files (by checking them in), so I can adapt them to my special needs
- I want to be able to contribute bindings back to BuckleTypes, without leaving my project repository
- I want my tool to detect dependencies of bindings inside bindings (mostly for ecosystem / plugin bindings... ala redux-saga -> redux, jquery-plugin-x -> jquery)

**Comment by chenglou** [comment]
@wokalski to be clear: an interop bs-foo in BuckleTypes modeling the foo as a dep doesn't make adopting it in an existing codebase harder (nor easier). `foo` will be shared, and if not, it won't be shared under other solutions either (we do care about interop!)

**Comment by wokalski** [comment]
@chenglou yes - what I was saying was that I approached the problem from that angle so I didn't see this solution.

**Comment by glennsl** [comment]
Closing for having outlived its usefulness, I think. Reopen if not.
